---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel7-01
  labels:
    app: rhel-fleet
    os: rhel7
spec:
  runStrategy: Always
  instancetype:
    name: u1.small
  preference:
    name: rhel.7
  dataVolumeTemplates:
    - metadata:
        name: rhel7-01-rootdisk
      spec:
        sourceRef:
          kind: DataSource
          name: rhel7 # platform-provided DataSource; see README one-time upload
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  template:
    metadata:
      labels:
        app: rhel-fleet
        os: rhel7
    spec:
      domain:
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: vm-dhcp-network
              bridge: {}
      networks:
        - name: vm-dhcp-network
          multus:
            networkName: vm-dhcp-network
      volumes:
        - name: rootdisk
          dataVolume:
            name: rhel7-01-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: cloudinit-rhel7
